# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Georgia food generator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Pods for Georgia food generator
pod 'SVGKit'

end
